export
    const 
    PLAYER_SPRITE_WIDTH = 84,
    PLAYER_SPRITE_HEIGHT = 128,
    PLAYER_SPRITE_STARTX = 330,
    PLAYER_SPRITE_STARTY = 10,
    PLAYER_HEIGHT = 60,
    PLAYER_WIDTH = 40,
    MAP_HEIGHT = 1100,
    MAP_WIDTH = 950,
    MAP_ZOOM = 3;
